.\" $Id$
.TH vpopbull 1
.SH NAME
vpopbull \- Delivers pop bulletins to virtual users
.SH SYNOPSIS
.B vpopbull
[
.B options
]
.I directory ...
[
.B -- command [ args ... ]
]
.SH DESCRIPTION
Scans the named bulletin directories for any bulletins which are newer
than the
.I .timestamp
file in the specified maildir.
For each bulletin that it finds, it adds a symlink to that bulletin to
the specified maildir.
Since no reformatting is done, these bulletins must be fully formatted
email messages, including full headers.
After it has finished, it updates the timestamp file.
.P
This program was designed to be run from
.IR checkvpw-postsetuid .
If the list of directories is followed by a command, it is executed
after the bulletins are delivered.  This allows it to be used directly
with qmail-pop3d or pop3front.
.SH RETURN VALUE
Exits false if an error occurred during startup, true otherwise.
.SH ENVIRONMENT
This program expects the environment variable
.I HOME
to be set, and executes a change directory to the contents of it
before starting.
.P
This program expects
.I MAILDIR
to be set, and delivers any bulletins that it finds into this maildir.
.SH SEE ALSO
checkvpw(1)
